
["Dynamic Chunk View Distance Settings"]
	#The maximum chunk view distance allowed to use. Set to the max a player could benefit from. Default: 20
	#Range: 1 ~ 200
	maxChunkViewDist = 20
	#The average tick time to stabilize the chunk view distance around. Setting it higher than 50ms is not advised, as after 50ms the TPS will go below 20. Default: 45ms
	#Range: 10 ~ 100
	meanAvgTickTime = 45
	#The minimum chunk view distance allowed to use. Default: 4
	#Range: 3 ~ 200
	minChunkViewDist = 5
	#Whether to output log messages for actions done. This can be helpful to balance the other settings nicely.
	logMessages = false
	#The update frequency of average server tick time checks to update view distances. Default: 30sec
	#Range: 1 ~ 1000
	viewDistanceUpdateRate = 30

["Chunk slow unload settings"]
	#Enable slow chunk unloading(~1minute) after load, helps with mods hot-loading chunks frequently. Default: true
	chunkunload = true

