#Enable or disable the entire engine
enabled = true
#Enable or disable a debug overlay that colors pixels by their normal
debugNormals = false
#Cache chunk lookups to improve performance.
chunkCaching = true

